### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by brylie** [akx/lepo#20]
The 'getting started' document says to add Lepo to the djangoo INSTALLED_APPS, but does not mention the recommended way to install Lepo to begin with. What steps should I take to install Lepo on my development system and within a django project?

**Comment by akx** [comment]
This is true. As it is, the document expects the reader to know their basic Python packaging tools (i.e. `pip` in this case). It could definitely be made better!

**Comment by brylie** [comment]
Cool. For context, I am coming from a JavaScript background. I am just recently transitioning to Python ecosystem.
