### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by brylie** [akx/lepo#21]
When running Lepo for the first time, I get the following error:

```py
.../lepo/router.py", line 48, in from_file
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

It would be useful if there were **explicit** installation instructions for setting up Lepo in a new django project. The requirements.txt does not seem to indicate that 'yaml' is a requirement.

**Comment by akx** [comment]
PyYAML is not a strict requirement; the Swagger file could be JSON as well as YAML. Good point though, the docs could be clearer about this.

**Comment by akx** [comment]
This relates to #20.
