### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by brylie** [akx/lepo#22]
When attempting to POST to a Lepo endpoint, I get the following error:

```
CSRF verification failed. Request aborted.

Reason given for failure:
    CSRF cookie not set.
```

I am calling directly from a REST client. How do I enable or bypass CSRF verification in a Lepo view?

**Comment by akx** [comment]
Preliminary support for decorating views (for e.g. marking them CSRF excempt) was added in [this commit](https://github.com/akx/lepo/commit/3d19632dcbaf9a2cd8dc9b2a5510f6f55c15175c#diff-65b0bebf20920cef1d54f67097d3fde0R76) and released in Lepo 0.1.0.

The TL;DR is that you want to turn `Router.get_urls()` into `Router.get_urls(decorate=(csrf_exempt,))`; that could be either Django's `csrf_exempt` or the simpler one available in `lepo.decorators`.

A related issue is #16.

**Comment by brylie** [comment]
Will this be added to the Lepo documentation? I am pretty new to Django in general, so explicit documentation is really helpful :-)

**Comment by akx** [comment]
Fair point. Reopening so I'll remember to write those docs.

**Comment by brylie** [comment]
Kiitos @akx :smile:
