### ISSUE TITLE
MissingParameter('parameter csv_url is required but missing',)}

### ISSUE THREAD

**Issue by brylie** [akx/lepo#23]
When calling a newly defined Lepo endpoint, based on a [this OpenAPI Spec file](https://github.com/apinf/ml-rest/blob/master/machine_learning_as_a_service/machine_learning_as_a_service/machine_learning_as_a_service-openapi_spec_v2.yaml), I am getting the following exception:

```
Exception Type: | ErroneousParameters
-- | --
({'csv_url': MissingParameter('parameter csv_url is required but missing',)}, {})
```

I am trying to pass in the `csv_url` parameter both in the header and query:

![peek 2017-08-14 13-16](https://user-images.githubusercontent.com/17307/29267780-e1183772-80f2-11e7-95a7-ea4922521f2d.gif)

How do I define and pass in parameters properly?

**Comment by akx** [comment]
The linked YAML does seem correct to me... The code that reads parameters from the headers is https://github.com/akx/lepo/blob/24b9c7b62181d124ae27997afe6d20f16f8e01ba/lepo/parameters.py#L114-L115 - what does the Django request META dictionary look like? Does it have `HTTP_CSV_URL`? I think it's available there in the debug error output.

**Comment by akx** [comment]
Ah! This is a [Django feature-of-sorts. Header names may not contain underscores.](https://github.com/django/django/commit/316b8d49746933d1845d600314b002d9b64d3e3d)

I'll add validation for this to `validate_router`.

**Comment by brylie** [comment]
OK, good to know. I'll revise the [OpenAPI document](https://github.com/apinf/ml-rest/blob/master/machine_learning_as_a_service/machine_learning_as_a_service/machine_learning_as_a_service-openapi_spec_v2.yaml) for this experiment.
