### ISSUE TITLE
Evaluate prance for ref-resolving Swagger/OpenAPI parsing

### ISSUE THREAD

**Issue by japsu** [akx/lepo#8]
Perhaps more skookum than rolling our own.

https://github.com/jfinkhaeuser/prance

**Comment by akx** [comment]
I'm a little bit wary about a resolver that blindly does HTTP requests to resolve those references...

Can you file an issue if you come across a case the current ref resolver doesn't like, and we can continue from there?

**Comment by akx** [comment]
So yeah, it turns out `jsonschema`'s RefResolver does this thing well.

It also does those HTTP requests, though.
